name: Alibaba.DingTalk 测试

on:
  workflow_dispatch:

jobs:
  on-windows:
    runs-on: windows-latest

    steps:
      - name: Install winget
        uses: Cyberboss/install-winget@v1

      - name: 设置 Rust
      # 用于后续的 `cargo binstall` 安装
        uses: cargo-bins/cargo-binstall@main
        env:
          GITHUB_TOKEN: ${{ github.token }}

      - name: 安装 Komac
        run: cargo binstall komac -y
        env:
          GITHUB_TOKEN: ${{ github.token }}

      - name: Run Test
        shell: pwsh
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: |-
          winget --info
          echo "====================="
          komac list-versions Alibaba.DingTalk | Sort-Object -Descending | `
          ForEach-Object {
            winget download -s winget -e --id Alibaba.DingTalk -d ./Temp -v $_;
            Write-Output ""
          }
