name: Pack Releases

on:
  workflow_dispatch:
    inputs:
      version:
        description: 版本号 (不带v)
        required: true
  release:
    types: [ published ]

jobs:
  pack-releases:
    runs-on: windows-latest

    steps:
      - name: 处理版本号
        shell: pwsh
        run: |
          if ($env:GITHUB_EVENT_NAME -eq "workflow_dispatch") {
            $version = "${{ github.event.inputs.version }}"
            # 如果版本号以 v 开头，则去掉 v
            if ($version.StartsWith("v")) {
              $version = $version.Substring(1)
            }
          } else {
            $version = "${{ github.ref_name }}"
            # 如果版本号以 refs/tags/ 开头，则去掉 refs/tags/
            if ($version.StartsWith("refs/tags/")) {
              $version = $version.Substring(10)
            }
            # 如果版本号以 v 开头，则去掉 v
            if ($version.StartsWith("v")) {
              $version = $version.Substring(1)
            }
          }
          Write-Host "Version: $version"
          # 将版本号写入环境变量
          Write-Output "VERSION=$version" | Out-File $env:GITHUB_ENV -Append

      - name: 检出代码
        uses: actions/checkout@v4
        with:
          repository: 'fjwxzde/Test'

      - name: 配置 Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.x

      - name: 清理待发布标签
        if: ${{ github.event_name != 'workflow_dispatch' }}
        shell: bash
        env:
          PYTHONIOENCODING: utf-8
          GH_TOKEN: ${{ github.token }}
        run: |
          python "自动化脚本/清理待发布标签.py" "${{ env.VERSION }}"
