name: 测试触发方式

on:
  workflow_dispatch:
    inputs:
      version:
        description: 版本号 (不带v)
        required: true
  release:
    types: [ published ]

jobs:
  on-windows:
    runs-on: ubuntu-latest

    steps:
      - name: 输出触发方式
        shell: bash
        run: |
          echo "触发方式: ${{ github.event_name }}"
          echo "版本号: ${{ github.ref_name }}"
          echo "发布版本: ${{ github.event.release.tag_name }}"
          echo "发布版本名称: ${{ github.event.release.name }}"
          echo "发布版本描述: ${{ github.event.release.body }}"

  on-linux:
    runs-on: ubuntu-latest

    steps:
      - name: 输出触发方式
        shell: bash
        run: |
          echo "触发方式: ${{ github.event_name }}"
          echo "版本号: ${{ github.ref_name }}"
          echo "发布版本: ${{ github.event.release.tag_name }}"
          echo "发布版本名称: ${{ github.event.release.name }}"
          echo "发布版本描述: ${{ github.event.release.body }}"

  on-macos:
    runs-on: macos-latest

    steps:
      - name: 输出触发方式
        shell: bash
        run: |
          echo "触发方式: ${{ github.event_name }}"
          echo "版本号: ${{ github.ref_name }}"
          echo "发布版本: ${{ github.event.release.tag_name }}"
          echo "发布版本名称: ${{ github.event.release.name }}"
          echo "发布版本描述: ${{ github.event.release.body }}"