name: Handle Auto Merge Labels

on:
  pull_request:
    types:
      - auto_merge_enabled
      - auto_merge_disabled

jobs:
  handle_auto_merge_labels:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Add or remove label based on auto-merge state
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          PR_NUMBER=${{ github.event.pull_request.number }}
          AUTO_MERGE_ENABLED=${{ github.event.pull_request.auto_merge_enabled }}

          if [ "$AUTO_MERGE_ENABLED" == "true" ]; then
            echo "[INFO] 已启用自动合并, 正在添加 'DEV-已启用自动合并' 标签..."
            gh pr edit $PR_NUMBER --add-label "DEV-已启用自动合并"
          else
            echo "[INFO] 自动合并已禁用, 正在移除 'DEV-已启用自动合并' 标签..."
            gh pr edit $PR_NUMBER --remove-label "DEV-已启用自动合并"
          fi
