name: 可用版本测试

on:
  workflow_dispatch:
    inputs:
      package-id:
        description: "软件包标识符"
        required: true

jobs:
  ok-version-test:
    runs-on: windows-latest

    steps:
      - name: 安装 WinGet
        uses: Cyberboss/install-winget@v1

      - name: 设置 Rust
      # 用于后续的 `cargo binstall` 安装
        uses: cargo-bins/cargo-binstall@main
        env:
          GITHUB_TOKEN: ${{ github.token }}

      - name: 安装 Komac
        run: cargo binstall komac -y
        env:
          GITHUB_TOKEN: ${{ github.token }}

      - name: 运行测试
        shell: pwsh
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: |-
          winget source update winget
          # 先更新源，避免下载进度条塞满日志
          winget --info
          echo "====================="
          komac list-versions ${{ inputs.package-id }} | Sort-Object -Descending | `
          ForEach-Object {
            winget download -s winget -e --id ${{ inputs.package-id }} -d ./Temp -v $_;
            Write-Output ""
          }
