name: 分析归档

on:
  workflow_dispatch:
    inputs:
      file:
        description: '需要获取的文件 URL'
        required: true

permissions:
  contents: read

jobs:
  download-and-upload:
    runs-on: windows-latest

    steps:
      - name: 下载文件
        shell: pwsh
        run: |
          # 使用 PowerShell 下载文件
          Invoke-WebRequest -Uri "${{ github.event.inputs.file }}" -OutFile "installer.zip"

      - name: 获取 SHA256
        shell: pwsh
        run: |
          Get-FileHash -Path "installer.zip"

      - name: 解压归档
        shell: pwsh
        run: |
          7z x installer.zip
          # 列出解压缩的文件
          Get-ChildItem -Path .

      - name: 测试运行
        shell: pwsh
        run: |
          spyserver.exe --version
