name: Test Run

on:
    workflow_dispatch:

permissions: {}

jobs:
  tests:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - windows-latest

    steps:
      - name: 检出代码
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          persist-credentials: false

      - name: 设置 .NET
        uses: actions/setup-dotnet@9a946fdbd5fb07b82b2f5a4466058b876ab72bb2 # v5.3.0
        with:
          dotnet-version: 10.x

      - name: 发布
        shell: pwsh
        run: dotnet publish ConsoleApp --configuration Release

      - name: (Windows) 添加发布目录到 PATH
        if: ${{ runner.os == 'Windows' }}
        shell: pwsh
        run: |-
          $publishPath = Join-Path -Path (Get-Location) -ChildPath 'ConsoleApp/bin/Release/net10.0'
          echo "PATH=$publishPath;$env:PATH" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append

      - name: (Linux) 添加发布目录到 PATH
        if: ${{ runner.os == 'Linux' }}
        shell: bash
        run: |-
          echo "PATH=$(pwd)/ConsoleApp/bin/Release/net10.0:$PATH" >> $GITHUB_ENV

      - name: 测试 - help
        shell: pwsh
        run: ConsoleApp
