name: 测试

on:
  workflow_dispatch:

permissions:
  contents: read
  issues: write

jobs:
  Retry:
    runs-on: ubuntu-latest

    steps:
      - name: 测试
        shell: bash
        run: gh issue create --body "test issue"
        
