name: WinGet PR 测试

on:
  workflow_dispatch:
    inputs:
      PR:
        description: 需要测试的 PR
        required: true

jobs:
  test:
    runs-on: windows-latest

    steps:
      - name: 安装 WinGet
        uses: Cyberboss/install-winget@v1

      - name: WinGet 基本信息
        shell: pwsh
        run: |-
          winget settings --enable LocalManifestFiles
          winget --info

      - name: 签出上游
        uses: actions/checkout@v4
        with:
          repository: microsoft/winget-pkgs
          # master 分支
          ref: master

      - name: 添加远程
        shell: pwsh
        run: |-
          git remote add fork https://github.com/DuckDuckStudio/winget-pkgs.git
          git fetch fork

      - name: 签出 PR
        shell: pwsh
        env:
          GH_TOKEN: ${{ github.token }}
        run: |- 
          gh repo set-default microsoft/winget-pkgs
          gh pr checkout "${{ inputs.PR }}"

      - name: 测试安装
        shell: pwsh
        run: |-
          winget uninstall --id Microsoft.WindowsADK
          New-Item -Path D:\Test -ItemType Directory
          New-Item -Path D:\Test\Installation -ItemType Directory
          winget install --manifest "manifests/m/Microsoft/WindowsADK/10.1.26100.2454/" -l D:\Test\Installation\
        continue-on-error: true

      - name: 验证可能的安装位置
        shell: pwsh
        run: |-
          Get-ChildItem -Path D:\Test\Installation\

      - name: 上传日志
        uses: actions/upload-artifact@v4
        with:
          name: winget-log
          path: C:\Users\runneradmin\AppData\Local\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\DiagOutputDir
