name: 测试

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: windows-latest

    steps:
    - name: Install winget Test
      uses: DuckDuckStudio/install-winget@test

    - name: Test
      shell: pwsh
      run: |
        winget --info
        winget search DuckStudio
