name: WinGet PR 测试

on:
  workflow_dispatch:
    inputs:
      PR:
        description: 需要测试的 PR
        required: true

jobs:
  test:
    runs-on: windows-latest

    steps:
      - name: 安装 WinGet
        uses: Cyberboss/install-winget@v1

      - name: WinGet 基本信息
        shell: pwsh
        run: winget --info

      - name: 签出上游
        uses: actions/checkout@v4
        with:
          repository: microsoft/winget-pkgs
          # master 分支
          ref: master

      - name: 添加远程
        shell: pwsh
        run: |-
          git remote add fork https://github.com/DuckDuckStudio/winget-pkgs.git
          git fetch fork

      - name: 签出 PR
        shell: pwsh
        env:
          GH_TOKEN: ${{ github.token }}
        run: |- 
          gh repo set-default microsoft/winget-pkgs
          gh pr checkout "${{ inputs.PR }}"

      - name: 对比差异
        # 得知需要测试的修改所在文件夹，并存到 GitHub_ENV 给后续 step 调用，以便后续 winget install --manifest <修改的文件夹>
        shell: pwsh
        run: |-
          $folder = (git diff --name-only HEAD^ HEAD | Select-String -Pattern 'manifests/.*\.json' | ForEach-Object { $_.ToString().Split('/')[1] }) -join ','
          echo "folder=$folder" >> $GITHUB_ENV

      - name: 测试 - 验证目录
        shell: pwsh
        run: |-
          Write-Host "需要测试的文件夹: ${{ env.folder }}"

      - name: 上传日志
        uses: actions/upload-artifact@v4
        with:
          name: winget-log
          path: C:\Users\runneradmin\AppData\Local\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\DiagOutputDir
